name: Coding Standards
on:
  pull_request:
  push:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP v7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install

  phpcs:
    name: PHP CS
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: PHP Coding Standards
        run: php ./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php --dry-run --verbose --diff --path-mode=intersection app/Models/Finance/Payment.php

  larastan:
    name: Larastan
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Larastan
        run: vendor/bin/phpstan analyse
